### ISSUE TITLE
Array

### ISSUE THREAD

**Issue by DieselDriver** [mikepultz/netdns2#115]
Hi,

in past time I run release 1.4.4 on server with PHP 5.3.3 without problems.

Now I tried to upgrade to release 1.5.0. It also runs after changing the short way of arrays to classic way.

**from**
```
... = []
```
**to**
```
... = array();
```

It seems that PHP 5.3.3 does not support the short notation like PHP 5.4+.
Maybe you can change it back to old "longer" syntax, then your code is more compatible. :-)

**Comment by mikepultz** [comment]
Hey @DieselDriver,

Yes- v1.5.0 and up require at least PHP 5.4.

Mike

**Comment by DieselDriver** [comment]
Your sources are also running with PHP 5.3.3 with longer array syntax.
So, why to change this when it is then only running with higher releases of PHP?

Maybe you can change it back to old "longer" syntax, then your code is more compatible.

**Comment by mikepultz** [comment]
PHP 5.3.3 is more than 10 years old, and is riddled with security exploits- I wouldn't recommend anybody run that.

The reason I did a major version jump, was because it could cause compatibly issues with people still running unsupported versions of PHP- so you can either keep using 1.4.x, or you can always fork 1.5.x yourself, and re-add the longer syntax- but I'm not going to go backwards in the main codebase.

Mike
