### ISSUE TITLE
TXT records does not display

### ISSUE THREAD

**Issue by sandoche2k** [mikepultz/netdns2#37]
$record->cname ==> results in the CNAME in the ANSWER section of the query
similarly 
$record->address ==> results in the IP address in the ANSWER section of the query
Whereas 
$record->text results in the response "Array"

Is this an issue in the code or i am initialising incorrectly. 
The initialising is done as following .. 
$result = $r->query($FQDN, 'TXT');

**Comment by mikepultz** [comment]
Hello,

Well, TXT entries are a little different, since you can specify more than one string in the value, by separating them by double quotes. So when the library parses the result, it stores it in an array to account for this:

http://www.zytrax.com/books/dns/ch8/txt.html

So $record->text is an array of values.

Mike
