### ISSUE TITLE
Add support for asynchronous sockets

### ISSUE THREAD

**Issue by cubiclesoft** [mikepultz/netdns2#48]
Net::DNS2 is currently not particularly friendly for PHP based server applications and wherever bulk lookups are needed due to only offering synchronous (aka blocking) sockets to users of the class.  My current workaround is to start background processes and then do the DNS lookups from there.  Of course, while it works, that's not a very efficient use of system resources.  It would be nice to tighten up some of my code.

Please add support for asynchronous (aka non-blocking) sockets.

Looking briefly at your code, async support will probably require a significant rewrite of sendPacket() and the various calls it makes to separate the various interests.  Async support generally works best as a state engine with transitioning between different states ('connecting', 'send request', 'get response', etc) and the async-enabled application repeatedly calls some sort of "resume" function/method to move through the various states whenever the application determines that the conditions for resuming have possibly been met (e.g. select() returns an indication that data *might* be available to be read).  The state engine, during each resume call, tries to move through as many states as possible.  When done properly, turning async support that uses a state engine into synchronous logic is usually just one line of code.

There are some odd issues that crop up when moving to async that, if you've never worked with async sockets before, you might find useful to know.  One issue is that a connection can appear to be "connected" but reading/writing might not be fully available because a TCP handshake hasn't completed (yet).  As a result, the class might need to hang around in the 'connecting' state across multiple calls.  Other states might have similar issues.  Just something to be aware of in order to keep each state small, light, fast, and bug-free.  Socket timeouts also have some gotchas when using async sockets.  (Note:  Under the hood, all sockets and file descriptors are actually asynchronous, but OSes and various languages add synchronous layers to make them easier to comprehend/use.)

The best async implementations also require exposing some class internals to the application or other classes.  Specifically, the underlying socket handle and the current internal request state need to be accessible.  This is necessary because async capable classes are rarely used in isolation and it is usually up to the application to orchestrate the appropriate state transitions, manage global timeouts, etc. - information which is generally beyond the scope of a single class.  For example, my own PHP MultiAsyncHelper class calls select() on all registered file and socket handles:

https://github.com/cubiclesoft/ultimate-web-scraper/blob/master/support/multi_async_helper.php

That class allows me to mix multiple handles for different classes and track ownership over the lifetime of each handle.  For MultiAsyncHelper (and other classes like it) to work, there needs to be a way to easily access underlying socket information.  I usually just bind MultiAsyncHelper support directly into my other classes, which, in turn, makes using async operations extremely simple and elegant at the application layer since I only use MultiAsyncHelper.  However, I don't necessarily recommend forcing MultiAsyncHelper on your users - I was just demonstrating the need for having methods to expose certain internal information for use by the application and other classes.

**Comment by mikepultz** [comment]
Hi @cubiclesoft,

I've already started work on this- sort of.

But to be clear- "async" is not the same thing as non-blocking; given that in *most* cases, you can't fork a process or spawn a thread in PHP, real "async" won't ever be possible. Also- while I'm using non-blocking sockets, there's ultimately no way to never "block"- calling select() blocks- so even your async_helper library blocks based on your timeout, since PHP will always be synchronous.

But I understand what you're saying.

The version I'm working on, simply allows users to pass an array of requests to the resolver, and the resolver will iterate through them, and send them all out on their own sockets, and then wait for responses using select().

I'm concerned that the extra overhead of cycling through creating sockets, managing the select() arrays, selecting, and triggering call-backs (assuming that's the way I'll return the data), will negate any gains in speed from doing them "in parallel" - my guess is, unless you're using some slow-ass name servers, or have a LOT of hosts to lookup, the gains will be marginal- but I'll know more once I have more of it built.

And given that the interface to it (how you provide hosts, and how you pull results), will likely be significantly different than the current resolver, I'll likely build it as a separate "multiResolve" class- or something like that.

Mike

**Comment by cubiclesoft** [comment]
I see you closed this issue.  What did you decide here?

I know I never responded but let's just say there could be upwards of 50,000 lookups performed in as parallel a fashion as possible for what I would like to use such a non-blocking feature for.  As the library is now, I can just fork off processes and then have each one of those processes pick off entries from a queue.  It's just more efficient if it all happens in a single process.
