### ISSUE TITLE
DNSSEC/DANE validation

### ISSUE THREAD

**Issue by renne** [mikepultz/netdns2#49]
Hi,

as all German mail providers have to support [DANE-SMTP (IETF RFC 7672)](https://tools.ietf.org/pdf/rfc7672) transport encryption to renew their data privacy/security certifications I suggest to add DNSSEC validation to netdns2.

[DANE-SMTP](https://tools.ietf.org/pdf/rfc7672) uses DNSSEC-secured TLSA-RRs to validate the TLS-certificates of mail-servers.

**Comment by mikepultz** [comment]
Yup- this is something that's been on the TODO list for a while- I'll have to check to see if there's enough functionality in the openssl library to support this.

**Comment by renne** [comment]
Have a look at [OpenSSL 1.1.0](https://www.openssl.org/docs/manmaster/ssl/SSL_dane_enable.html). ;-)

**Comment by mikepultz** [comment]
Yeah, it's easy to do in C, since the functions are built right into the OpenSSL library, but none of this is exported to PHP, so it's not accessible.

Thinking about this more, I don't think it makes sense to add DANE validation into NetDNS2; NetDNS2 is a DNS resolver- it doesn't make sense to add functionality that's protocol specific (i.e. HTTP, SMTP, etc.) into the library.

It makes more sense to me that this would be a separate package, that uses NetDNS2 for DNS lookups, but the purpose of the library to is to validate certificates. The challenge is getting the certificate, and generating the fingerprint. There isn't any socket functionality in the PHP OpenSSL implementation that I'm aware of either- so I'm not sure how you would get the TLS socket from the remote server.

Mike
