### ISSUE TITLE
Replacement for rawQuery?

### ISSUE THREAD

**Issue by Daniel15** [mikepultz/netdns2#63]
The documentation for Net_DNS2 says "Near drop-in replacement for Net_DNS". I'm trying to upgrade a 10-year-old site from Net_DNS to Net_DNS2, but it's throwing this error:

```
Fatal error: Call to undefined method Net_DNS2_Resolver::rawQuery() in C:\src\dnstools.ws\public\tools\lookup.php on line 59
```

What's the replacement for `rawQuery`?

**Comment by mikepultz** [comment]
Well, the key word there is "near" ;)

There isn't an exact replacement for rawQuery()- the only difference between Query() and rawQuery() in Net_DNS is that Query() will return false on error, while rawQuery() will return whatever response is returned- whether it's valid or not- or even an object at all.

In Net_DNS2, a Net_DNS2_Exception is thrown on error, and both the request and response objects are available on the exception object using $e->getRequest() and $e->getResponse(), which gives you the same (more) information as rawQuery(), while moving to an exception block, rather than just returning false, or having two different functions.

Mike

**Comment by Daniel15** [comment]
Thanks for the information! Sounds like I can just use a try-catch block and look at the response on error. That's what I was looking for. 😃
