### ISSUE TITLE
Unable to use hostname for DNS server

### ISSUE THREAD

**Issue by Daniel15** [mikepultz/netdns2#64]
I have some code using the legacy Net_DNS library to perform a DNS lookup directly at the root DNS servers, using `a.root-servers.net` through `m.root-servers.net` as the nameservers. This code works in Net_DNS, but in Net_DNS2 it throws this error:

```
Fatal error:  Uncaught exception 'Net_DNS2_Exception' with message 'invalid address type: j.root-servers.net' in C:\src\dnstools.ws\vendor\pear\net_dns2\Net\DNS2.php:1333
Stack trace:
#0 C:\src\dnstools.ws\vendor\pear\net_dns2\Net\DNS2.php(972): Net_DNS2-&gt;sendUDPRequest('j.root-servers....', '\xBDH\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x07ex...')
#1 C:\src\dnstools.ws\vendor\pear\net_dns2\Net\DNS2\Resolver.php(212): Net_DNS2-&gt;sendPacket(Object(Net_DNS2_Packet_Request), false)
#2 C:\src\dnstools.ws\public\tools\lookup.php(59): Net_DNS2_Resolver-&gt;query('example.com', 'A')
#3 C:\src\dnstools.ws\public\tools\lookup.php(42): do_lookup(Array)
#4 {main}
  thrown in C:\src\dnstools.ws\vendor\pear\net_dns2\Net\DNS2.php on line 1333

```

**Comment by mikepultz** [comment]
Hey @Daniel15,

You can't make a request using a host name as a DNS server- what you would need to do, is first do a A record lookup for the root name server, and then use that IP as the DNS server for the subsequent request.

This was intentionally left out of Net_DNS2 because of the obvious circular problem. If you look at the Net_DNS code, it creates another instance of Net_DNS within itself, using the default options- which means you can't control which DNS servers get used to do the lookup of the root name server (not to mention any of the other configuration options)- it relies on the fact that it will load /etc/resolv.conf by default- which doesn't always work / isn't always desirable.

Doing the lookup first is the exactly same number DNS requests, but it lets the user control the configuration of all the DNS requests.

Mike

**Comment by Daniel15** [comment]
Thanks for the information! I appreciate your time :)
