### ISSUE TITLE
Feature request: RFC3597 support

### ISSUE THREAD

**Issue by gbxyz** [mikepultz/netdns2#94]
I am planning to implement this feature request myself and will create a pull request when ready, but wanted to float it for review first.

I'd like my application to be able to support RR types that might not be known to `Net_DNS2` - either because they are new and support hasn't been added, or because they are unstandardised implementation-specific records.

I'm proposing to implement RFC 3597 in `Net_DNS2` (for unknown RR types; I don't propose implementing support for unknown classes).

I propose upating `Net_DNS2_RR::parse()`, in the case where the integer value of the RR type isn't associated with a class name in `Net_DNS2_Lookups::$rr_types_id_to_class`.

Instead of throwing an exception, `parse()` would do something like this:

```php
if (isset($class)) {
    // known type, proceed as normal
    $o = new $class($packet, $object);

} else {

    // generate a type name as per RFC 3597
    $type = sprintf('TYPE%u', $object['type']);

    // generate a class name derived from the class
    $class = 'Net_DNS2_RR_'.$type;

    // dynamically create this class using eval()
    if (!class_exists($class)) eval(sprintf('class %s extends Net_DNS2_RR_Unknown {}', $class));

    // inject information into Net_DNS2_Lookups:
    Net_DNS2_Lookups::$rr_types_by_id[$object['type']]       = $type;
    Net_DNS2_Lookups::$rr_types_by_name[$type]               = $object['type'];
    Net_DNS2_Lookups::$rr_types_class_to_id[$class]          = $object['type'];
    Net_DNS2_Lookups::$rr_types_id_to_class[$object['type']] = $class;

    // create RR
    $o = new $class($packet, $object);

}
```

The `Net_DNS2_RR_Unknown` record would implement the necessary abstract methods to read/write presentation and wire format data as per RFC 3597.

Question: WDYT? I am not hugely keen on the `eval()` but am not sure how else to dynamically create the class.

Question: should this be something that should only work if explicitly enabled?

**Comment by mikepultz** [comment]
hey @gbxyz 

So i think adding it is a good idea; the eval() stuff kinda freaks me out though- I would see if you can do it either as a stdClass- but I don't know if that lets you extend the Net_DNS2_RR_Unknown object- or try using anonymous classes- this would work:

`$o = new class($packet, $object) extends Net_DNS2_RR_Unknown {};`

but that will only work in PHP 7 and up, and the object name would be "class@anonymous", so caching might be a problem.

Otherwise, you could just try modifying the code so it uses "Net_DNS2_RR_Unknown" directly for any unknown type- I know the Net_DNS2_Lookups entries are used in a few places, but i'm not sure if it actually matters what the class name is? 

```
if (isset($class)) {
    // known type, proceed as normal
    $o = new $class($packet, $object);

} else {

    // generate a type name as per RFC 3597
    $type = sprintf('TYPE%u', $object['type']);

    // generate a class name derived from the class
    $class = 'Net_DNS2_RR_Unknown';

    // inject information into Net_DNS2_Lookups:
    Net_DNS2_Lookups::$rr_types_by_id[$object['type']]       = $type;
    Net_DNS2_Lookups::$rr_types_by_name[$type]               = $object['type'];
    Net_DNS2_Lookups::$rr_types_class_to_id[$class]          = $object['type'];
    Net_DNS2_Lookups::$rr_types_id_to_class[$object['type']] = $class;

    // create RR
    $o = new $class($packet, $object);
}
```




Maybe it can be that simple.

The other issue, is the Question object is parsed before the RR entries are- and it validates that it's a know type and throws an exception if it's not found- so a lot of this will probably need to move to the Question object.

Another concern is that there might be people that expect the library to throw an exception on unknown types- so yes, it might make sense to make it so you have to enable this feature, and it's off by default- otherwise it could break some things.

Let me know what you think-

Mike

**Comment by gbxyz** [comment]
Since I posted this issue I've dived in and pretty much implemented what I outlined above. Have a look [here](https://github.com/mikepultz/netdns2/compare/master...gbxyz:master). I am hoping to be able to submit a pull request soon.

* the behaviour must be explicitly enabled by setting a static class property:

    ```php
    Net_DNS2::$allow_unknown_records = true;
    ```

It's a static class property rather than an object property, because my application uses `Net_DNS2` without instantiating a `Net_DNS2_Resolver`. It's not the neatest approach but `Net_DNS2` doesn't have any other configuration interfaces that aren't specific to `Net_DNS2_Resolver`.

* the changes I've made fully implement RFC3597 for unknown RR types, so unknown types can be used when doing queries, when RRs are instantiated from presentation format input, and from binary data on the wire. I've added a unit test which exercises all of those use cases - are there any I've missed?

* my personal feeling is that a new class should be instantiated for each new unknown RR type; that is symmetrical with how known RR types are handled and allows for introspection, etc.

* regarding the `eval()`, it is locked up inside `Net_DNS2_RR_RFC3597::register()` (the changes to the existing code in `Net_DNS2` are actually quite small) and the class name is carefully validated to elminate any security risk. So I think it's safe to use, even if a bit icky, and I don't think there are any performance implications.

**Comment by mikepultz** [comment]
Hey @gbxyz -

I appreciate your effort, but there's no way I can pull your changes in.

* Your static config option is different than every other config option in the class; I appreciate that's the way you use it, but that's weird for everybody else.
* You can easily inject arbitrary PHP code to eval() through the register function- so that's a pretty big security hole. I don't think I would ever pull in code that used eval()- there's always a better way of doing that.
* You didn't really put any effort into making your code align with the surrounding code- your style is completely different.

If you can adjust, I'd be happy to reconsider for inclusion.

Mike

**Comment by gbxyz** [comment]
Hi Mike, thanks for the feedback.

> * Your static config option is different than every other config option in the class; I appreciate that's the way you use it, but that's weird for everybody else.

What's the right way to do it? Should I make it a configuration option on `Net_DNS2`/`Net_DNS2_Resolver`?

> * You can easily inject arbitrary PHP code to eval() through the register function- so that's a pretty big security hole. I don't think I would ever pull in code that used eval()- there's always a better way of doing that.

The input that is used to construct the class name is either an `int` or a `string` matching the pattern `/^TYPE(\d+)$/` but I appreciate you position on the use of the `eval()`. I will continue to think about alternative approaches.

> * You didn't really put any effort into making your code align with the surrounding code- your style is completely different.

I tried to get things like whitespace right but looking again I think my editor defeated me. I'll take another look and will make sure the style matches the existing practices.

**Comment by gbxyz** [comment]
I'm going to close this issue, I've decided to take a different approach and implement RFC3597 support in a separate repository, which may be found here:

https://gitlab.centralnic.com/centralnic/netdns2_rfc3597

Thanks for your patience with me!
